import './globals.css'

export const metadata = {
  title: 'FindRepo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt_BR">
      <body>
        {children}
      </body>
    </html>
  )
}
